version: "3"

services:
  
  api:
    build:
      dockerfile: ./docker/api/Dockerfile.local
    container_name: ${PROJECT_NAME}-api
    volumes:
      - ./api:${API_DIRECTORY}
    networks:
      - ${PROJECT_NAME}

#  frontend:
#    build: ./frontend
#    container_name: ${PROJECT_NAME}-frontend
#    networks:
#      courselab:
#        ipv4_address: ${FRONTEND_IPV4}
#
#  nginx:
#    build:
#      context: ./docker/nginx
#    container_name: ${PROJECT_NAME}-nginx
#    volumes:
#      - ./api:${API_DIRECTORY}
#      - ./frontend:${FRONTEND_DIRECTORY}
#    depends_on:
#      - api
#    environment:
#      FRONTEND_DIRECTORY: ${FRONTEND_DIRECTORY}
#      API_DIRECTORY: ${API_DIRECTORY}
#    networks:
#      courselab:
#        ipv4_address: ${NGINX_IPV4}


volumes:
  api:
  nginx:
  data:

networks:
  courselab:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.22.75.0/16
